(self.AMP=self.AMP||[]).push({n:"amp-form",v:"1499361527811",f:(function(AMP){var l;function m(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]}function n(a,b){return b.length>a.length?!1:0==a.lastIndexOf(b,0)};var aa=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;var ba=Object.prototype.toString;function ca(a){if(!a)return[];for(var b=Array(a.length),c=0;c<a.length;c++)b[c]=a[c];return b};Date.now();self.log=self.log||{user:null,dev:null};var q=self.log;function r(){if(q.user)return q.user;throw Error("failed to call initLogConstructor");};var da=Object.prototype.hasOwnProperty;
function ea(a,b){var c=Number.POSITIVE_INFINITY,d=[],e=[{target:a,source:b,depth:0}];for(a={};0<e.length;){b=e.shift();a.h=b.target;a.b=b.source;a.depth=b.depth;if(d.includes(a.b))throw Error("Source object contains circular references");d.push(a.b);a.h!==a.b&&(a.depth>c?Object.assign(a.h,a.b):(Object.keys(a.b).forEach(function(a){return function(b){var c=a.b[b];if(da.call(a.h,b)){var d=a.h[b];if("[object Object]"===ba.call(c)&&"[object Object]"===ba.call(d)){e.push({target:d,source:c,depth:a.depth+
1});return}}a.h[b]=c}}(a)),a={b:a.b,h:a.h,depth:a.depth}))}};var t=self.AMP_CONFIG||{},fa=("string"==typeof t.cdnProxyRegex?new RegExp(t.cdnProxyRegex):t.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org/;var u,v;
function w(a){var b;u||(u=self.document.createElement("a"),v=self.UrlCache||(self.UrlCache=Object.create(null)));var c=v[a];if(c)return c;var d=u;d.href=a;d.protocol||(d.href=d.href);var e={href:d.href,protocol:d.protocol,host:d.host,hostname:d.hostname,port:"0"==d.port?"":d.port,pathname:d.pathname,search:d.search,hash:d.hash,origin:null};"/"!==e.pathname[0]&&(e.pathname="/"+e.pathname);if("http:"==e.protocol&&80==e.port||"https:"==e.protocol&&443==e.port)e.port="",e.host=e.hostname;e.origin=d.origin&&
"null"!=d.origin?d.origin:"data:"!=e.protocol&&e.host?e.protocol+"//"+e.host:e.href;var g=e,f=g;return b?f:v[a]=f}function ga(a){"string"==typeof a&&(a=w(a));var b;(b="https:"==a.protocol||"localhost"==a.hostname)||(a=a.hostname,b=a.length-10,b=0<=b&&a.indexOf(".localhost",b)==b);return b}
function ha(a,b,c){c=void 0===c?"source":c;r().assert(null!=a,"%s %s must be available",b,c);var d=a;r().assert(ga(d)||/^(\/\/)/.test(d),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',b,c,d)}function ia(a){"string"==typeof a&&(a=w(a));return fa.test(a.origin)};function ja(a,b){if(a.nodeType){var c=(a.ownerDocument||a).defaultView;if(c=c!=(c.__AMP_TOP||c)&&ka(c,b)?y(c,b):null)return c}return z(a,b)}function A(a,b){a=a.__AMP_TOP||a;return y(a,b)}function z(a,b){a=B(a);a=C(a);return y(a,b)}function B(a){return a.nodeType?A((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function C(a){a=B(a);return a.isSingleDoc()?a.win:a}
function y(a,b){ka(a,b);var c=D(a);a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function la(a){var b=ma(a);if(b)return b;var c,d=new Promise(function(a){c=a});D(a)["amp-analytics-instrumentation"]={obj:null,promise:d,resolve:c,context:null,ctor:null};return d}
function ma(a){var b=D(a)["amp-analytics-instrumentation"];if(b){if(b.promise)return b.promise;y(a,"amp-analytics-instrumentation");return b.promise=Promise.resolve(b.obj)}return null}function D(a){var b=a.services;b||(b=a.services={});return b}function ka(a,b){a=a.services&&a.services[b];return!(!a||!a.ctor&&!a.obj)};var E=null;Promise.resolve();
function na(a){var b;if(!E){E=Object.create(null);if(a.AMP_CONFIG)for(b in a.AMP_CONFIG){var c=a.AMP_CONFIG[b];"number"===typeof c&&0<=c&&1>=c&&(E[b]=Math.random()<c)}if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-doc-opt-in"])&&0<a.AMP_CONFIG["allow-doc-opt-in"].length&&(b=a.AMP_CONFIG["allow-doc-opt-in"],c=a.document.head.querySelector('meta[name="amp-experiments-opt-in"]')))for(var c=c.getAttribute("content").split(","),d=0;d<c.length;d++)-1!=b.indexOf(c[d])&&(E[c[d]]=!0);Object.assign(E,oa(a));
if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-url-opt-in"])&&0<a.AMP_CONFIG["allow-url-opt-in"].length){b=a.AMP_CONFIG["allow-url-opt-in"];c=a.location.originalHash||a.location.hash;a=Object.create(null);if(c)for(var e;e=aa.exec(c);)d=decodeURIComponent(e[1]).trim(),e=e[2]?decodeURIComponent(e[2]).trim():"",a[d]=e;for(c=0;c<b.length;c++)d=a["e-"+b[c]],"1"==d&&(E[b[c]]=!0),"0"==d&&(E[b[c]]=!1)}}b=E;var g=b;return!!g["amp-form-verifiers"]}
function oa(a){a:{var b;b:{try{b=a.document.cookie;break b}catch(f){}b=void 0}if(a=b)for(a=a.split(";"),b=0;b<a.length;b++){var c=a[b].trim(),d=c.indexOf("=");if(-1!=d&&"AMP_EXP"==decodeURIComponent(c.substring(0,d).trim())){a=decodeURIComponent(c.substring(d+1).trim());break a}}a=null}var e=a,g=e?e.split(/\s*,\s*/g):[];a=Object.create(null);for(b=0;b<g.length;b++)0!=g[b].length&&("-"==g[b][0]?a[g[b].substr(1)]=!1:a[g[b]]=!0);return a};var F;function pa(a,b){for(var c=[],d=a.parentElement;d;d=d.parentElement)b(d)&&c.push(d);return c}function qa(a){var b="fieldset",b=b.toUpperCase();return pa(a,function(a){return a.tagName==b})}function G(a,b){for(var c=0,d;void 0!==(d=a[c]);c++)b(d,c)};function ra(a){return a.ampExtendedElements?!!a.ampExtendedElements["amp-analytics"]:!1}function sa(a){var b=B(a),c=ma(C(a));return c?c:Promise.resolve().then(function(){return ra(b.win)?la(C(a)):b.whenBodyAvailable().then(function(){return ra(b.win)?la(C(a)):null})})};var H,ta="Webkit webkit Moz moz ms O o".split(" ");function ua(a,b){for(var c in b){var d=a,e=b[c],g;g=d.style;var f=c;if(n(f,"--"))g=f;else{H||(H=Object.create(null));var h=H[f];if(!h){h=f;if(void 0===g[f]){var k;k=f;k=k.charAt(0).toUpperCase()+k.slice(1);b:{for(var p=0;p<ta.length;p++){var x=ta[p]+k;if(void 0!==g[x]){k=x;break b}}k=""}void 0!==g[k]&&(h=k)}H[f]=h}g=h}g&&(d.style[g]=e)}};function va(a,b){var c,d,e="form.amp-form-submit-error [submit-error],form.amp-form-submit-success [submit-success],form.amp-form-submitting [submitting]{display:block}.i-amphtml-validation-bubble{-webkit-transform:translate(-50%,-100%);transform:translate(-50%,-100%);background-color:#fff;box-shadow:0 5px 15px 0 rgba(0,0,0,.5);max-width:200px;position:absolute;display:none;box-sizing:border-box;padding:10px;border-radius:5px}.i-amphtml-validation-bubble:after{content:' ';position:absolute;bottom:-8px;left:30px;width:0;height:0;border-left:8px solid transparent;border-right:8px solid transparent;border-top:8px solid #fff}[visible-when-invalid]{display:none;color:red}[visible-when-invalid].visible{display:initial}\n/*# sourceURL=/extensions/amp-form/0.1/amp-form.css*/",
g=wa(a,a.head,e,c||!1,d||null);if(xa(a,g))b(g);else var f=setInterval(function(){xa(a,g)&&(clearInterval(f),b(g))},4)}
function wa(a,b,c,d,e){if(d&&b.runtimeStyleElement)return b.runtimeStyleElement;if(b.parentElement&&b.parentElement.hasAttribute("i-amphtml-layout")&&(d||e&&"amp-custom"!=e)){var g=d?b.querySelector("style[amp-runtime]"):b.querySelector("style[amp-extension="+e+"]");if(g)return d&&(b.runtimeStyleElement=g),g}a=a.createElement("style");a.textContent=c;var f=null;d?(a.setAttribute("amp-runtime",""),b.runtimeStyleElement=a):"amp-custom"==e?(a.setAttribute("amp-custom",""),f=b.lastChild):(a.setAttribute("amp-extension",
e||""),f=b.runtimeStyleElement);c=b;var h=f;h?h.nextSibling?c.insertBefore(a,h.nextSibling):c.appendChild(a):c.insertBefore(a,c.firstChild);return a}function xa(a,b){var c=a.styleSheets;for(a=0;a<c.length;a++){var d=c[a];if(d.ownerNode==b)return!0}return!1};function ya(a,b,c,d){var e={detail:c};Object.assign(e,d);if("function"==typeof a.CustomEvent)return new a.CustomEvent(b,e);a=a.document.createEvent("CustomEvent");a.initCustomEvent(b,!!e.bubbles,!!e.cancelable,c);return a};function I(a){var b,c;this.L=new Promise(function(a,d){b=a;c=d});this.V=b;this.T=c;this.D=0;if(a)for(var d=0;d<a.length;d++)this.add(a[d])}I.prototype.add=function(a){var b=this,c=++this.D;Promise.resolve(a).then(function(a){b.D===c&&b.V(a)},function(a){b.D===c&&b.T(a)});return this.L};I.prototype.then=function(a,b){return this.L.then(a,b)};function J(a,b,c){sa(a).then(function(d){d&&d.triggerEventForTarget(a,b,c)})};/*

 Copyright (c) 2014 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
var Ba={strictStyling:!1,scopeRules:function(a,b,c){var d="";a&&Array.prototype.forEach.call(a,function(a){if(a.selectorText&&a.style&&void 0!==a.style.cssText)d+=this.scopeSelector(a.selectorText,b,this.strictStyling,c)+" {\n\t",d+=this.propertiesFromRule(a)+"\n}\n\n";else if(a.type===CSSRule.MEDIA_RULE)d+="@media "+a.media.mediaText+" {\n",d+=this.scopeRules(a.cssRules,b),d+="\n}\n\n";else try{a.cssText&&(d+=a.cssText+"\n\n")}catch(g){a.type===CSSRule.KEYFRAMES_RULE&&a.cssRules&&(d+=this.ieSafeCssTextFromKeyFrameRule(a))}},
this);return d},ieSafeCssTextFromKeyFrameRule:function(a){var b="@keyframes "+a.name+" {";Array.prototype.forEach.call(a.cssRules,function(a){b+=" "+a.keyText+" {"+a.style.cssText+"}"});return b+=" }"},scopeSelector:function(a,b,c,d){var e=[];a.split(",").forEach(function(a){a=a.trim();d&&(a=d(a));this.selectorNeedsScoping(a,b)&&(a=c&&!a.match(za)?this.applyStrictSelectorScope(a,b):this.applySelectorScope(a,b));e.push(a)},this);return e.join(", ")},selectorNeedsScoping:function(a,b){if(Array.isArray(b))return!0;
var c=this.makeScopeMatcher(b);return!a.match(c)},makeScopeMatcher:function(a){a=a.replace(/\[/g,"\\[").replace(/\]/g,"\\]");return new RegExp("^("+a+")"+Aa,"m")},applySelectorScope:function(a,b){return Array.isArray(b)?this.applySelectorScopeList(a,b):this.applySimpleSelectorScope(a,b)},applySelectorScopeList:function(a,b){for(var c=[],d=0,e;e=b[d];d++)c.push(this.applySimpleSelectorScope(a,e));return c.join(", ")},applySimpleSelectorScope:function(a,b){return a.match(K)?(a=a.replace(za,b),a.replace(K,
b+" ")):b+" "+a},applyStrictSelectorScope:function(a,b){b=b.replace(/\[is=([^\]]*)\]/g,"$1");var c=[" ",">","+","~"],d=a,e="["+b+"]";c.forEach(function(a){d=d.split(a).map(function(a){var b=a.trim().replace(K,"");b&&0>c.indexOf(b)&&0>b.indexOf(e)&&(a=b.replace(/([^:]*)(:*)(.*)/,"$1"+e+"$2$3"));return a}).join(a)});return d},propertiesFromRule:function(a){var b=a.style.cssText;a.style.content&&!a.style.content.match(/['"]+|attr/)&&(b=b.replace(/content:[^;]*;/g,"content: '"+a.style.content+"';"));
a=a.style;for(var c in a)"initial"===a[c]&&(b+=c+": initial; ");return b}},Aa="([>\\s~+[.,{:][\\s\\S]*)?$",za="-shadowcsshost-no-combinator",K=/-shadowcsshost/gim;var L;function Ca(a){return!!a&&-1!==a.toString().indexOf("[native code]")};var Da=/[^\.\-\_0-9a-zA-Z]/,Ea=/[^\-\_0-9a-zA-Z]/;function Fa(a){return a.replace(/(html|body)/g,Ga)}function Ga(a,b,c,d){var e=d.charAt(c-1),g=d.charAt(c+a.length);return e&&!Da.test(e)||g&&!Ea.test(g)?a:"amp-"+a}
function Ha(a){var b=a.createElement("style");b.textContent="form.amp-form-submit-error [submit-error],form.amp-form-submit-success [submit-success],form.amp-form-submitting [submitting]{display:block}.i-amphtml-validation-bubble{-webkit-transform:translate(-50%,-100%);transform:translate(-50%,-100%);background-color:#fff;box-shadow:0 5px 15px 0 rgba(0,0,0,.5);max-width:200px;position:absolute;display:none;box-sizing:border-box;padding:10px;border-radius:5px}.i-amphtml-validation-bubble:after{content:' ';position:absolute;bottom:-8px;left:30px;width:0;height:0;border-left:8px solid transparent;border-right:8px solid transparent;border-top:8px solid #fff}[visible-when-invalid]{display:none;color:red}[visible-when-invalid].visible{display:initial}\n/*# sourceURL=/extensions/amp-form/0.1/amp-form.css*/";try{return(a.head||
a.documentElement).appendChild(b),b.sheet?b.sheet.cssRules:null}finally{b.parentNode&&b.parentNode.removeChild(b)}};function Ia(a){var b=a.ownerDocument.defaultView;b.FormProxy||(b.FormProxy=Ja(b));var c=b.FormProxy,b=new c(a);"action"in b||Ka(a,b);a.$p=b}
function Ja(a){function b(a){this.a=a}var c=b.prototype,d=[a.HTMLFormElement,a.HTMLElement,a.Element,a.Node,a.EventTarget];d.forEach(function(b){var d=b&&b.prototype,e={},h;for(h in d)if(e.property=a.Object.getOwnPropertyDescriptor(d,h),e.property&&h.toUpperCase()!=h&&!n(h,"on")&&!a.Object.prototype.hasOwnProperty.call(c,h)){if("function"==typeof e.property.value)e.method=e.property.value,c[h]=function(a){return function(){return a.method.apply(this.a,arguments)}}(e);else{var k={};e.property.get&&
(k.get=function(a){return function(){return a.property.get.call(this.a)}}(e));e.property.set&&(k.set=function(a){return function(b){return a.property.set.call(this.a,b)}}(e));a.Object.defineProperty(c,h,k)}e={method:e.method,property:e.property}}});return b}
function Ka(a,b){var c=a.ownerDocument.defaultView.HTMLFormElement.prototype.cloneNode.call(a,!1),d={},e;for(e in c)if(d.name=e,!(d.name in b||d.name.toUpperCase()==d.name||n(d.name,"on"))){d.desc=La[d.name];c=a[d.name];if(d.desc)if(d.desc.access==M){d.actual=void 0;if(c&&c.nodeType){var g=c.nextSibling,f=c.parentNode;f.removeChild(c);try{d.actual=a[d.name]}finally{f.insertBefore(c,g)}}else d.actual=c;Object.defineProperty(b,d.name,{get:function(a){return function(){return a.actual}}(d)})}else d.desc.access==
N&&(d.attr=d.desc.attr||d.name,Object.defineProperty(b,d.name,{get:function(a){return function(){var c=b.getAttribute(a.attr);null==c&&void 0!==a.desc.def?c=a.desc.def:a.desc.type==Ma?c="true"===c:a.desc.type==O?c=null!=c:a.desc.type==Na&&(c=w(c||"").href);return c}}(d),set:function(a){return function(c){a.desc.type==O&&(c=c?"":null);null!=c?b.setAttribute(a.attr,c):b.removeAttribute(a.attr)}}(d)}));else Object.defineProperty(b,d.name,{get:function(b){return function(){return a[b.name]}}(d),set:function(b){return function(c){a[b.name]=
c}}(d)});d={actual:d.actual,attr:d.attr,desc:d.desc,name:d.name}}}
var N=1,M=2,Na=1,Ma=2,O=3,La={acceptCharset:{access:N,attr:"accept-charset"},accessKey:{access:N,attr:"accesskey"},action:{access:N,type:Na},attributes:{access:M},autocomplete:{access:N,def:"on"},children:{access:M},dataset:{access:M},dir:{access:N},draggable:{access:N,type:Ma,def:!1},elements:{access:M},encoding:{access:M},enctype:{access:N},hidden:{access:N,type:O,def:!1},id:{access:N,def:""},lang:{access:N},localName:{access:M},method:{access:N,def:"get"},name:{access:N},noValidate:{access:N,attr:"novalidate",
type:O,def:!1},prefix:{access:M},spellcheck:{access:N},style:{access:M},target:{access:N,def:""},title:{access:N},translate:{access:N}};function P(a,b){this.I=b;this.aa=z(a,"viewport");this.A=A(a.win,"vsync");this.G=null;this.F="";this.u=!1;this.j=a.win.document.createElement("div");this.j.classList.add("i-amphtml-validation-bubble");this.j.__BUBBLE_OBJ=this;a.getBody().appendChild(this.j)}P.prototype.isActiveOn=function(a){return this.u&&a==this.G};P.prototype.hide=function(){this.u&&(this.u=!1,this.G=null,this.F="",this.A.run({measure:void 0,mutate:Oa},{bubbleElement:this.j}))};
P.prototype.show=function(a,b){if(!this.isActiveOn(a)||b!=this.F){this.u=!0;this.G=a;this.F=b;var c={message:b,targetElement:a,bubbleElement:this.j,viewport:this.aa,id:this.I};this.A.run({measure:Pa,mutate:Qa},c)}};function Oa(a){a.bubbleElement.removeAttribute("aria-alert");a.bubbleElement.removeAttribute("role");for(var b=a.bubbleElement;b.firstChild;)b.removeChild(b.firstChild);ua(a.bubbleElement,{display:"none"})}function Pa(a){a.targetRect=a.viewport.getLayoutRect(a.targetElement)}
function Qa(a){for(var b=a.bubbleElement;b.firstChild;)b.removeChild(b.firstChild);var c=a.bubbleElement.ownerDocument.createElement("div");c.id="bubble-message-"+a.id;c.textContent=a.message;a.bubbleElement.setAttribute("aria-labeledby",c.id);a.bubbleElement.setAttribute("role","alert");a.bubbleElement.setAttribute("aria-live","assertive");a.bubbleElement.appendChild(c);ua(a.bubbleElement,{display:"block",top:a.targetRect.top-10+"px",left:a.targetRect.left+a.targetRect.width/2+"px"})};var Q,Ra,Sa=0;function R(a){this.form=a;this.ampdoc=A((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a);this.doc=a.ownerDocument}R.prototype.report=function(){};R.prototype.onBlur=function(){};R.prototype.onInput=function(){};function Ta(a){R.apply(this,arguments)}m(Ta,R);Ta.prototype.report=function(){this.form.reportValidity()};function S(a){R.call(this,a);var b="i-amphtml-validation-bubble-"+Sa++;this.l=new P(this.ampdoc,b)}m(S,R);
S.prototype.report=function(){for(var a=this.form.querySelectorAll("input,select,textarea"),b=0;b<a.length;b++)if(!a[b].checkValidity()){a[b].focus();this.l.show(a[b],a[b].validationMessage);break}};S.prototype.onBlur=function(){this.l.hide()};S.prototype.onInput=function(a){a=a.target;this.l.isActiveOn(a)&&(a.checkValidity()?(a.removeAttribute("aria-invalid"),this.l.hide()):(a.setAttribute("aria-invalid","true"),this.l.show(a,a.validationMessage)))};
function T(a){R.call(this,a);this.J={};this.s={}}m(T,R);l=T.prototype;l.reportInput=function(a){var b;a:{for(b in a.validity)if(a.validity[b])break a;b=null}var c=b;c&&this.showValidationFor(a,c)};l.hideAllValidations=function(){for(var a in this.s){var b=this.doc.getElementById(a);this.hideValidationFor(b)}};l.getValidationFor=function(a,b){if(!a.id)return null;a="[visible-when-invalid="+b+"]"+("[validation-for="+a.id+"]");void 0===this.J[a]&&(this.J[a]=this.doc.querySelector(a));return this.J[a]};
l.showValidationFor=function(a,b){var c=this.getValidationFor(a,b);c&&(c.textContent.trim()||(c.textContent=a.validationMessage),a.setAttribute("aria-invalid","true"),c.classList.add("visible"),this.s[a.id]=c)};l.hideValidationFor=function(a){var b=this.getVisibleValidationFor(a);b&&(a.removeAttribute("aria-invalid"),b.classList.remove("visible"),delete this.s[a.id])};l.getVisibleValidationFor=function(a){return a.id?this.s[a.id]:null};
l.shouldValidateOnInteraction=function(){throw Error("Not Implemented");};l.onInteraction=function(a){a=a.target;var b=this.shouldValidateOnInteraction(a);this.hideValidationFor(a);b&&!a.checkValidity()&&this.reportInput(a)};l.onBlur=function(a){this.onInteraction(a)};l.onInput=function(a){this.onInteraction(a)};function U(a){T.apply(this,arguments)}m(U,T);
U.prototype.report=function(){this.hideAllValidations();for(var a=this.form.querySelectorAll("input,select,textarea"),b=0;b<a.length;b++)if(!a[b].checkValidity()){this.reportInput(a[b]);a[b].focus();break}};U.prototype.shouldValidateOnInteraction=function(a){return!!this.getVisibleValidationFor(a)};function V(a){T.apply(this,arguments)}m(V,T);
V.prototype.report=function(){this.hideAllValidations();for(var a=null,b=this.form.querySelectorAll("input,select,textarea"),c=0;c<b.length;c++)b[c].checkValidity()||(a=a||b[c],this.reportInput(b[c]));a&&a.focus()};V.prototype.shouldValidateOnInteraction=function(a){return!!this.getVisibleValidationFor(a)};function Ua(a){T.apply(this,arguments)}m(Ua,T);Ua.prototype.shouldValidateOnInteraction=function(){return!0};
function Va(a){var b=a.getAttribute("custom-validation-reporting");switch(b){case "as-you-go":return new Ua(a);case "show-all-on-submit":return new V(a);case "show-first-on-submit":return new U(a)}a.ownerDocument&&void 0===Q&&(Q=!!document.createElement("form").reportValidity);return Q?new Ta(a):new S(a)};function Wa(a,b){var c=a.ownerDocument.defaultView;return a.hasAttribute("verify-xhr")?(r().assert(na(c),'Enable "amp-form-verifiers" experiment to use form verifiers'),new Xa(a,b)):new Ya(a)}function W(a){this.a=a}W.prototype.onCommit=function(){Za(this);return $a(this)?this.P():Promise.resolve([])};W.prototype.P=function(){return Promise.resolve([])};
function $a(a){a=a.a.elements;for(var b=0;b<a.length;b++){var c=a[b];if(!c.disabled)switch(c.type){case "select-multiple":case "select-one":for(var c=c.options,d=0;d<c.length;d++)if(c[d].selected!==c[d].defaultSelected)return!0;break;case "checkbox":case "radio":if(c.checked!==c.defaultChecked)return!0;break;default:if(c.value!==c.defaultValue)return!0}}return!1}function Za(a){(a=a.a.elements)&&G(a,function(a){a.setCustomValidity("")})}function Ya(a){W.apply(this,arguments)}m(Ya,W);
function Xa(a,b){this.a=a;this.o=b;this.m=null;this.K=[]}m(Xa,W);Xa.prototype.P=function(){var a=this,b=this.o().then(function(){return[]},function(a){return ab(a)});return bb(this,b).then(function(b){return cb(a,b)})};function bb(a,b){if(!a.m){a.m=new I;var c=function(){return a.m=null};a.m.then(c,c)}return a.m.add(b)}
function cb(a,b){function c(a){return b.every(function(b){return a.name!==b.name})}var d=[],e=a.K;a.K=b;for(var g=0;g<b.length;g++){var f=b[g],h=r().assertString(f.name,"Verification errors must have a name property"),f=r().assertString(f.message,"Verification errors must have a message property"),h=r().assertElement(a.a.querySelector('[name="'+h+'"]'),"Verification error name property must match a field name");h.checkValidity()&&(h.setCustomValidity(f),d.push(h))}var k=e.filter(c).map(function(b){return a.a.querySelector('[name="'+
b.name+'"]')});return d.concat(k)}function ab(a){return(a=a.response)?a.json().then(function(a){return a.verifyErrors||[]},function(){return[]}):Promise.resolve([])};var db=["amp-selector"];
function eb(a,b){var c=this;try{Ia(a)}catch(g){var d;if(q.dev)d=q.dev;else throw Error("failed to call initLogConstructor");d.error("amp-form","form proxy failed to install",g)}a.__AMP_FORM=this;this.I=b;this.c=a.ownerDocument.defaultView;this.Z=A(this.c,"timer");this.O=ja(a,"url-replace");this.H=null;this.a=a;this.A=A(this.c,"vsync");this.N=A(this.c,"templates");this.ea=A(this.c,"xhr");this.C=ja(this.a,"action");this.W=z(this.a,"resources");this.i=(this.a.getAttribute("method")||"GET").toUpperCase();
this.Y=this.a.getAttribute("target");this.B=fb(this,"action-xhr");this.da=fb(this,"verify-xhr");this.fa=void 0;this.M=!this.a.hasAttribute("novalidate");this.a.setAttribute("novalidate","");this.M||this.a.setAttribute("amp-novalidate","");this.a.classList.add("i-amphtml-form");var e=this.a.querySelectorAll('[type="submit"]');this.X=ca(e);this.g="initial";a=this.a.elements;for(b=0;b<a.length;b++)d=a[b].name,r().assert("__amp_source_origin"!=d&&"__amp_form_verify"!=d,"Illegal input name, %s found: %s",
d,a[b]);this.w=Va(this.a);this.$=Wa(this.a,function(){return gb(c)});this.C.installActionHandler(this.a,this.R.bind(this),2);hb(this);this.U=this.ca=null}function fb(a,b){var c=a.a.getAttribute(b);c&&(ha(c,a.a,b),r().assert(!ia(c),"form "+b+" should not be on AMP CDN: %s",a.a));return c}l=eb.prototype;l.R=function(a){var b=this;"submit"==a.method&&ib(this).then(function(){var c=a;"submitting"!=b.g&&jb(b)&&(kb(b,c.trust),"GET"!=b.i||b.B||b.a.submit())})};
function ib(a){if(a.H)return a.H;var b=a.a.querySelectorAll(db.join(",")),c=ca(b).map(function(a){return a.whenBuilt()});return a.H=lb(a,c,2E3)}
function hb(a){function b(){"verifying"===a.g&&X(a,"initial")}a.a.addEventListener("submit",a.S.bind(a),!0);a.a.addEventListener("blur",function(b){Y(b.target);a.w.onBlur(b)},!0);a.a.addEventListener("change",function(c){a.$.onCommit().then(function(b){b.forEach(Y);a.w.onBlur(c)},function(){Y(c.target)}).then(b,b)});a.a.addEventListener("input",function(b){Y(b.target);a.w.onInput(b)})}
function mb(a){var b={},c=nb(a),d;for(d in c)Object.prototype.hasOwnProperty.call(c,d)&&(b["formFields["+d+"]"]=c[d].join(","));b.formId=a.a.id;J(a.a,"amp-form-submit",b)}l.S=function(a){"submitting"!=this.g&&jb(this)?((this.B||"POST"==this.i)&&a.preventDefault(),kb(this,2)):(a.stopImmediatePropagation(),a.preventDefault())};
function kb(a,b){var c=ob(a);if(a.B)pb(a,c,b);else if("POST"==a.i)r().assert(!1,"Only XHR based (via action-xhr attribute) submissions are support for POST requests. %s",a.a);else if("GET"==a.i){for(var d=c,e=0;e<d.length;e++)a.O.expandInputValueSync(d[e]);mb(a)}}function ob(a){return a.a.querySelectorAll('[type="hidden"][data-amp-replace]')}
function gb(a){if("submitting"===a.g)return Promise.resolve();X(a,"verifying");return qb(a,ob(a)).then(function(){var b={};return a.o(a.da,a.i,(b.__amp_form_verify=!0,b))})}function pb(a,b,c){X(a,"submitting");qb(a,b).then(function(){mb(a);a.C.trigger(a.a,"submit",null,c);var b=nb(a);rb(a,b)}).then(function(){return a.o(a.B,a.i)}).then(function(b){return sb(a,b)},function(b){return tb(a,b)})}
function qb(a,b){for(var c=[],d=0;d<b.length;d++)c.push(a.O.expandInputValueAsync(b[d]));return lb(a,c,100)}
l.o=function(a,b,c){var d,e,g="GET"==b||"HEAD"==b;if(g){var f=nb(this);c&&ea(f,c);var h=[],k;for(k in f){var p=f[k];if(null!=p)if(Array.isArray(p))for(var x=0;x<p.length;x++){var yb=p[x];h.push(encodeURIComponent(k)+"="+encodeURIComponent(yb))}else h.push(encodeURIComponent(k)+"="+encodeURIComponent(p))}(k=h.join("&"))?(a=a.split("#",2),f=a[0].split("?",2),k=f[0]+(f[1]?"?"+f[1]+"&"+k:"?"+k),d=k+=a[1]?"#"+a[1]:""):d=a}else for(f in d=a,e=new FormData(this.a),c)e.append(f,c[f]);return this.ea.fetch(d,
{body:e,method:b,credentials:"include",headers:{Accept:"application/json"}})};function sb(a,b){return b.json().then(function(c){ub(a,!0,c);J(a.a,"amp-form-submit-success",void 0);X(a,"submit-success");rb(a,c||{});vb(a,b)},function(a){r().error("amp-form","Failed to parse response JSON: "+a)})}
function tb(a,b){return(b&&b.response?b.response.json().catch(function(){return null}):Promise.resolve(null)).then(function(c){ub(a,!1,c);J(a.a,"amp-form-submit-error",void 0);X(a,"submit-error");rb(a,c||{});vb(a,b.response);r().error("amp-form","Form submission failed: "+b)})}function jb(a){void 0===Ra&&(Ra=!!a.c.document.createElement("input").checkValidity);if(Ra){var b=wb(a.a);if(a.M&&!b)return a.A.run({measure:void 0,mutate:xb},{validator:a.w}),!1}return!0}
function vb(a,b){if(b&&b.headers){var c=b.headers.get("AMP-Redirect-To");if(c){r().assert("_blank"!=a.Y,"Redirecting to target=_blank using AMP-Redirect-To is currently not supported, use target=_top instead. %s",a.a);try{b=c,r().assert(/^https?\:/i.test(b),'URL must start with "http://" or "https://". Invalid value: %s',b),w(b),ha(c,"AMP-Redirect-To","Url")}catch(d){r().assert(!1,"The `AMP-Redirect-To` header value must be an absolute URL starting with https://. Found %s",c)}a.c.top.location.href=
c}}}function ub(a,b,c){var d=b?"submit-success":"submit-error";c=ya(a.c,"amp-form."+d,{response:c});a.C.trigger(a.a,d,c,2)}function lb(a,b,c){return Promise.race([Promise.all(b),a.Z.promise(c)])}
function nb(a){var b={};a=a.a.elements;for(var c=/^(?:input|select|textarea)$/i,d=/^(?:button|image|file|reset)$/i,e=/^(?:checkbox|radio)$/i,g=0;g<a.length;g++){var f=a[g],h;if(h=f.name){a:if(f.disabled)h=!0;else{h=qa(f);for(var k=0;k<h.length;k++)if(h[k].disabled){h=!0;break a}h=!1}h=!h}!h||!c.test(f.tagName)||d.test(f.type)||e.test(f.type)&&!f.checked||(void 0===b[f.name]&&(b[f.name]=[]),b[f.name].push(f.value))}return b}
function X(a,b){var c=a.g;a.a.classList.remove("amp-form-"+c);a.a.classList.add("amp-form-"+b);zb(a,c);a.g=b;a.X.forEach(function(a){"submitting"==b?a.setAttribute("disabled",""):a.removeAttribute("disabled")})}
function rb(a,b){var c=a.a.querySelector("["+a.g+"]");if(c){var d="rendered-message-"+a.I;c.setAttribute("role","alert");c.setAttribute("aria-labeledby",d);c.setAttribute("aria-live","assertive");a.N.hasTemplate(c)?a.N.findAndRenderTemplate(c,b).then(function(b){b.id=d;b.setAttribute("i-amphtml-rendered","");c.appendChild(b);var e=ya(a.c,"amp:template-rendered",null,{bubbles:!0});c.dispatchEvent(e)}):(a.W.mutateElement(c,function(){}),Promise.resolve())}}
function zb(a,b){if(a=a.a.querySelector("["+b+"]")){if(null==F)try{a.ownerDocument.querySelector(":scope"),F=!0}catch(d){F=!1}F?a=a.querySelector(":scope > [i-amphtml-rendered]"):(a.classList.add("i-amphtml-scoped"),b=a.querySelector(".i-amphtml-scoped > [i-amphtml-rendered]"),a.classList.remove("i-amphtml-scoped"),a=b);var c=a;c&&(a=c,a.parentElement&&a.parentElement.removeChild(a))}}l.ha=function(){return this.ca};l.ga=function(){return this.U};function xb(a){a.validator.report()}
function wb(a){var b=a.querySelectorAll("input,select,textarea,fieldset");G(b,function(a){return Z(a)});return Z(a)}
function Z(a,b){b=void 0===b?!1:b;if(!a.checkValidity)return!0;var c=!1,d=a.classList.contains("user-valid")?"valid":a.classList.contains("user-invalid")?"invalid":"none",e=a.checkValidity();"valid"!=d&&e?(a.classList.add("user-valid"),a.classList.remove("user-invalid"),c="invalid"==d):"invalid"==d||e||(a.classList.add("user-invalid"),a.classList.remove("user-valid"),c=!0);if(a.validity)for(var g in a.validity)a.classList.toggle(g,a.validity[g]);if(b&&c){g=qa(a);for(var f=0;f<g.length;f++)Z(g[f]);
a.form&&Z(a.form)}return e}function Y(a){Z(a,!0)}function Ab(a){this.ba=Bb(a).then(function(){return Cb(a)})}Ab.prototype.whenInitialized=function(){return this.ba};
function Bb(a){return new Promise(function(b){if(a.isSingleDoc()){var c=a.getRootNode();va(c,b)}else{var c=a.getRootNode(),d=c.ownerDocument,e;void 0===L&&(Ca(self.document.registerElement)||Ca(self.Object.getOwnPropertyDescriptor(self,"customElements").get)?(e=Element,e=e.prototype.attachShadow?"v1":e.prototype.createShadowRoot?"v0":"none"):e="none",L=e);if("none"!=L)e="form.amp-form-submit-error [submit-error],form.amp-form-submit-success [submit-success],form.amp-form-submitting [submitting]{display:block}.i-amphtml-validation-bubble{-webkit-transform:translate(-50%,-100%);transform:translate(-50%,-100%);background-color:#fff;box-shadow:0 5px 15px 0 rgba(0,0,0,.5);max-width:200px;position:absolute;display:none;box-sizing:border-box;padding:10px;border-radius:5px}.i-amphtml-validation-bubble:after{content:' ';position:absolute;bottom:-8px;left:30px;width:0;height:0;border-left:8px solid transparent;border-right:8px solid transparent;border-top:8px solid #fff}[visible-when-invalid]{display:none;color:red}[visible-when-invalid].visible{display:initial}\n/*# sourceURL=/extensions/amp-form/0.1/amp-form.css*/";
else{e=c.id;var g=c.ownerDocument,f=null;try{f=Ha(g.implementation.createHTMLDocument(""))}catch(h){}if(!f)try{f=Ha(g)}catch(h){}e=f?Ba.scopeRules.call(Ba,f,"#"+e,Fa):"form.amp-form-submit-error [submit-error],form.amp-form-submit-success [submit-success],form.amp-form-submitting [submitting]{display:block}.i-amphtml-validation-bubble{-webkit-transform:translate(-50%,-100%);transform:translate(-50%,-100%);background-color:#fff;box-shadow:0 5px 15px 0 rgba(0,0,0,.5);max-width:200px;position:absolute;display:none;box-sizing:border-box;padding:10px;border-radius:5px}.i-amphtml-validation-bubble:after{content:' ';position:absolute;bottom:-8px;left:30px;width:0;height:0;border-left:8px solid transparent;border-right:8px solid transparent;border-top:8px solid #fff}[visible-when-invalid]{display:none;color:red}[visible-when-invalid].visible{display:initial}\n/*# sourceURL=/extensions/amp-form/0.1/amp-form.css*/"}wa(d,
c,e,!1,null);b()}})}function Cb(a){return a.whenReady().then(function(){Db(a.getRootNode().querySelectorAll("form"));Eb(a.getRootNode())})}function Db(a){a&&G(a,function(a,c){var b=a.__AMP_FORM||null;b||new eb(a,"amp-form-"+c)})}function Eb(a){a.addEventListener("amp:dom-update",function(){Db(a.querySelectorAll("form"))})}AMP.registerServiceForDoc("amp-form",Ab);
})});
//# sourceMappingURL=amp-form-0.1.js.map
