(self.AMP=self.AMP||[]).push({n:"amp-lightbox",v:"1499361527811",f:(function(AMP){var e;function h(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var f=Object.getOwnPropertyDescriptor(b,d);f&&Object.defineProperty(a,d,f)}else a[d]=b[d]};Date.now();self.log=self.log||{user:null,dev:null};function l(a,b){a=a.__AMP_TOP||a;return m(a,b)}function n(a){a=p(a);a=p(a);a=a.isSingleDoc()?a.win:a;return m(a,"history")}function p(a){return a.nodeType?l((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function m(a,b){var c=a.services;c||(c=a.services={});var d=c;a=d[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj};function q(){this.g=null}e=q.prototype;e.add=function(a){var b=this;this.g||(this.g=[]);this.g.push(a);return function(){b.remove(a)}};e.remove=function(a){this.g&&(a=this.g.indexOf(a),-1<a&&this.g.splice(a,1))};e.removeAll=function(){this.g&&(this.g.length=0)};e.fire=function(a){if(this.g)for(var b=this.g,c=0;c<b.length;c++)(0,b[c])(a)};e.getHandlerCount=function(){return this.g?this.g.length:0};var r,t="Webkit webkit Moz moz ms O o".split(" ");function u(a,b,c){var d;var f=a.style;if(2>b.length||0!=b.lastIndexOf("--",0)){r||(r=Object.create(null));var g=r[b];if(!g){g=b;if(void 0===f[b]){var k=b.charAt(0).toUpperCase()+b.slice(1);b:{for(var v=0;v<t.length;v++){var D=t[v]+k;if(void 0!==f[D]){k=D;break b}}k=""}void 0!==f[k]&&(g=k)}r[b]=g}b=g}b&&(a.style[b]=d?c+d:c)}function w(a){var b={display:"",opacity:0,transition:"opacity 0.1s ease-in"},c;for(c in b)u(a,c,b[c])};function x(a,b,c){var d=this;this.ha=l(a,"timer");this.la=b;this.ka=c||0;this.A=-1;this.P=0;this.W=!1;this.ia=function(){return d.L()}}x.prototype.isPending=function(){return-1!=this.A};x.prototype.schedule=function(a){var b=a||this.ka;this.W&&10>b&&(b=10);var c=Date.now()+b;return!this.isPending()||-10>c-this.P?(this.cancel(),this.P=c,this.A=this.ha.delay(this.ia,b),!0):!1};x.prototype.L=function(){this.A=-1;this.P=0;this.W=!0;this.la();this.W=!1};
x.prototype.cancel=function(){this.isPending()&&(this.ha.cancel(this.A),this.A=-1)};function y(a,b,c,d){this.type=a;this.data=b;this.time=c;this.event=d}
function z(a,b){this.i=a;this.b=[];this.D=[];this.h=[];this.a=[];this.c=null;this.qa=b;this.N=!1;this.L=new x(a.ownerDocument.defaultView,this.ca.bind(this));this.ea=new q;this.R=Object.create(null);this.ba=this.pa.bind(this);this.$=this.na.bind(this);this.aa=this.oa.bind(this);this.Z=this.ma.bind(this);this.i.addEventListener("touchstart",this.ba);this.i.addEventListener("touchend",this.$);this.i.addEventListener("touchmove",this.aa);this.i.addEventListener("touchcancel",this.Z);this.S=!1}
function A(a){var b=a.__AMP_Gestures;b||(b=new z(a,!1),a.__AMP_Gestures=b);return b}e=z.prototype;e.cleanup=function(){this.i.removeEventListener("touchstart",this.ba);this.i.removeEventListener("touchend",this.$);this.i.removeEventListener("touchmove",this.aa);this.i.removeEventListener("touchcancel",this.Z);delete this.i.__AMP_Gestures;this.L.cancel()};e.onGesture=function(a,b){var c=new a(this),d=c.getType(),f=this.R[d];f||(this.b.push(c),f=new q,this.R[d]=f);return f.add(b)};e.onPointerDown=function(a){return this.ea.add(a)};
e.pa=function(a){var b=Date.now();this.N=!1;this.ea.fire(a);for(var c=0;c<this.b.length;c++)if(!this.h[c]&&(this.a[c]&&this.a[c]<b&&B(this,c),this.b[c].onTouchStart(a))){var d=c;this.D[d]=!0;this.a[d]=0}C(this,a)};e.oa=function(a){for(var b=Date.now(),c=0;c<this.b.length;c++)this.D[c]&&(this.a[c]&&this.a[c]<b?B(this,c):this.b[c].onTouchMove(a)||B(this,c));C(this,a)};
e.na=function(a){for(var b=Date.now(),c=0;c<this.b.length;c++)this.D[c]&&(this.a[c]&&this.a[c]<b?B(this,c):(this.b[c].onTouchEnd(a),(!this.a[c]||this.a[c]<b)&&B(this,c)));C(this,a)};e.ma=function(a){for(var b=0;b<this.b.length;b++){var c=b;this.h[c]=0;B(this,c)}C(this,a)};function C(a,b){var c=!!a.c||a.N;a.N=!1;if(!c)for(var d=Date.now(),f=0;f<a.b.length;f++)if(a.h[f]||a.a[f]&&a.a[f]>=d){c=!0;break}c&&(b.stopPropagation(),a.qa||b.preventDefault());a.S&&(a.S=!1,a.ca())}
e.ca=function(){for(var a=Date.now(),b=-1,c=0;c<this.b.length;c++)if(!this.h[c])this.a[c]&&this.a[c]<a&&B(this,c);else if(-1==b||this.h[c]>this.h[b])b=c;if(-1!=b){for(var d=0,c=0;c<this.b.length;c++)!this.h[c]&&this.D[c]&&(d=Math.max(d,this.a[c]-a));if(2>d){for(var a=b,c=this.b[a],f=0;f<this.b.length;f++)if(f!=a){var g=f;this.h[g]=0;B(this,g)}this.h[a]=0;this.a[a]=0;this.c=c;c.acceptStart()}else this.L.schedule(d)}};function B(a,b){a.D[b]=!1;a.a[b]=0;a.h[b]||a.b[b].acceptCancel()}
function E(a,b){this.ra=a;this.K=b}e=E.prototype;e.getType=function(){return this.ra};e.signalReady=function(a){var b=this.K;if(b.c)this.acceptCancel();else{for(var c=Date.now(),d=0;d<b.b.length;d++)b.b[d]==this&&(b.h[d]=c+a,b.a[d]=0);b.S=!0}};e.signalPending=function(a){var b=this.K;if(b.c)this.acceptCancel();else for(var c=Date.now(),d=0;d<b.b.length;d++)b.b[d]==this&&(b.a[d]=c+a)};e.signalEnd=function(){var a=this.K;a.c==this&&(a.c=null,a.N=!0)};
e.signalEmit=function(a,b){var c=this.K.R[this.getType()];c&&c.fire(new y(this.getType(),a,Date.now(),b))};e.acceptStart=function(){};e.acceptCancel=function(){};e.onTouchStart=function(){return!1};e.onTouchMove=function(){return!1};e.onTouchEnd=function(){};function F(a,b,c){1>b&&(b=1);var d=a/b,f=.5+Math.min(b/33.34,.5);return d*f+c*(1-f)};function G(a,b,c,d){E.call(this,a,b);this.I=c;this.M=d;this.c=!1;this.s=this.o=this.T=this.J=this.ga=this.V=this.U=this.w=this.u=this.C=this.B=0}h(G,E);e=G.prototype;e.onTouchStart=function(a){a=a.touches;if(!a||1!=a.length)return!1;this.ga=Date.now();this.B=a[0].clientX;this.C=a[0].clientY;return!0};
e.onTouchMove=function(a){var b=a.changedTouches||a.touches;if(b&&1==b.length){var c=b[0].clientX,b=b[0].clientY;this.u=c;this.w=b;if(this.c)H(this,!1,!1,a);else if(a=Math.abs(c-this.B),c=Math.abs(b-this.C),this.I&&this.M)(8<=a||8<=c)&&this.signalReady(-10);else if(this.I)if(8<=a&&a>c)this.signalReady(-10);else{if(8<=c)return!1}else if(this.M)if(8<=c&&c>a)this.signalReady(-10);else{if(8<=a)return!1}else return!1}return!0};e.onTouchEnd=function(a){this.c&&(this.c=!1,H(this,!1,!0,a),this.signalEnd())};
e.acceptStart=function(){this.c=!0;this.U=this.B;this.V=this.C;this.T=this.ga;this.B=this.u;this.C=this.w;H(this,!0,!1,null)};e.acceptCancel=function(){this.c=!1};function H(a,b,c,d){a.J=Date.now();var f=a.J-a.T;if(!c&&4<f||c&&16<f)a.o=F(a.u-a.U,f,a.o),a.s=F(a.w-a.V,f,a.s),a.o=1E-4<Math.abs(a.o)?a.o:0,a.s=1E-4<Math.abs(a.s)?a.s:0,a.U=a.u,a.V=a.w,a.T=a.J;a.signalEmit({first:b,last:c,time:a.J,deltaX:a.I?a.u-a.B:0,deltaY:a.M?a.w-a.C:0,velocityX:a.I?a.o:0,velocityY:a.M?a.s:0},d)}
function I(a){G.call(this,"swipe-xy",a,!0,!0)}h(I,G);function J(a){AMP.BaseElement.call(this,a);this.H=this.l=this.Y=null;this.O=-1;this.F=!1;this.G=null;this.j=!1;this.da=this.m=0;this.X=null}h(J,AMP.BaseElement);e=J.prototype;e.isLayoutSupported=function(a){return"nodisplay"==a};
function K(a){if(!a.l&&(a.j=a.element.hasAttribute("scrollable"),a.H=a.getRealChildren(),a.l=a.element.ownerDocument.createElement("div"),a.j||a.applyFillContent(a.l),a.element.appendChild(a.l),a.H.forEach(function(b){a.j&&a.setAsOwner(b);a.l.appendChild(b)}),a.j&&a.element.addEventListener("scroll",a.fa.bind(a)),a.registerAction("open",a.activate.bind(a)),a.registerAction("close",a.close.bind(a)),!a.j)){var b=A(a.element);b.onGesture(I,function(){})}}e.layoutCallback=function(){return Promise.resolve()};
e.activate=function(){var a=this;this.F||(K(this),this.G=this.ja.bind(this),this.win.document.documentElement.addEventListener("keydown",this.G),this.getViewport().enterLightboxMode(this.element).then(function(){return L(a)}))};
function L(a){a.j&&u(a.element,"webkitOverflowScrolling","touch");a.mutateElement(function(){w(a.element);l(a.win,"vsync").mutate(function(){u(a.element,"opacity","")})}).then(function(){var b=a.l;a.j?(a.fa(),M(a,a.m,a.m)):a.updateInViewport(b,!0);a.scheduleLayout(b);a.scheduleResume(b)});n(a.getAmpDoc()).push(a.close.bind(a)).then(function(b){a.O=b});a.F=!0}e.ja=function(a){27==a.keyCode&&this.close()};
e.close=function(){var a=this;this.F&&(this.j&&u(this.element,"webkitOverflowScrolling",""),this.getViewport().leaveLightboxMode(this.element).then(function(){a.collapse();-1!=a.O&&n(a.getAmpDoc()).pop(a.O);a.win.document.documentElement.removeEventListener("keydown",a.G);a.G=null;a.schedulePause(a.l);a.F=!1}))};e.fa=function(){var a=this.element.scrollTop||1;this.m=this.element.scrollTop=a;null===this.X&&N(this,a)};
function N(a,b){a.X=l(a.win,"timer").delay(function(){if(30>Math.abs(b-a.m)){a.X=null;var c=a.m;M(a,c,a.da);a.da=c;a.m=c}else N(a,a.m)},100)}function M(a,b,c){var d=[];O(a,b,function(b){d.push(b);a.updateInViewport(b,!0)});c!=b&&O(a,c,function(b){d.includes(b)||a.updateInViewport(b,!1)})}function O(a,b,c){a.Y||(a.Y={width:a.element.clientWidth,height:a.element.clientHeight});for(var d=a.Y.height,f=0;f<a.H.length;f++){var g=a.H[f];g.offsetTop+g.offsetHeight>=b&&g.offsetTop<=b+d&&c(g)}}
AMP.registerElement("amp-lightbox",J,"amp-lightbox{display:none;position:fixed!important;z-index:1000;top:0!important;left:0!important;bottom:0!important;right:0!important}amp-lightbox[scrollable]{overflow-y:auto!important;overflow-x:hidden!important}\n/*# sourceURL=/extensions/amp-lightbox/0.1/amp-lightbox.css*/");
})});
//# sourceMappingURL=amp-lightbox-0.1.js.map
